### ISSUE TITLE
Bad code

### ISSUE THREAD

**Issue by EthanRStokes** [FrozenBlock/frozenblock.net#4]
This is a quick code review

Some code and all comments not in English: https://github.com/FrozenBlock/frozenblock.net/blob/5b2d8b0f66c0577b508b2203978f54e36fd33f7d/assets/frozenblock/textures/render/skin.js#L17

Meaningless function name (did you take this code?): https://github.com/FrozenBlock/frozenblock.net/blob/5b2d8b0f66c0577b508b2203978f54e36fd33f7d/js/index.js#L10

Weird variable name: https://github.com/FrozenBlock/frozenblock.net/blob/5b2d8b0f66c0577b508b2203978f54e36fd33f7d/js/mod/index.js#L47

Other:
Is the use of the Minecraft fonts infringement?

**Comment by LIUKRAST** [comment]
1- The skin.js is not currently in use and yes i wrote all the code, i just had no ideas for functions names

2- I have no idea about the minecraft font licence. Note that FrozenBlock's font is also under [license](https://www.dafont.com/wayfarer-s-toy-box.font)
